"""
Transformer script for: Vezora/Tested-143k-Python-Alpaca
Generated by Dataset Converter Pipeline
"""
import json
import logging
from typing import Any, Dict, List, Optional, Tuple, Iterable

# --- Plan from Kimi ---
PLAN = {
    "confirmed": true,
    "content_key": null,
    "conversation_field_candidates": [],
    "field_to_role": {
        "input": "user",
        "instruction": "user",
        "output": "assistant"
    },
    "notes": [
        "Dataset follows the Alpaca format: instruction + optional input form the user message, output is the assistant response.",
        "The 'input' field is frequently empty and should be skipped when empty.",
        "No system message field exists in the source data.",
        "User message construction: concatenate 'instruction' and 'input' (when non-empty) with a separator.",
        "Assistant message is directly taken from the 'output' field."
    ],
    "ordered_top_level_fields": [
        "instruction",
        "input",
        "output"
    ],
    "role_aliases": {
        "assistant": [],
        "system": [],
        "tool": [],
        "user": []
    },
    "role_key": null,
    "strategy": "flat_columns"
}

# --- Standard Normalization Functions ---

TARGET_ROLES = ("system", "user", "assistant", "tool")

ROLE_ALIASES = {
    "system": {"system", "sys", "instruction", "prompt", "context"},
    "user": {"user", "human", "client", "customer", "question", "input"},
    "assistant": {"assistant", "gpt", "bot", "ai", "model", "completion", "answer", "response"},
    "tool": {"tool", "function", "tool_call", "tool_result", "observation", "plugin"},
}

ROLE_KEY_CANDIDATES = ("role", "from", "speaker", "author", "sender", "type")
CONTENT_KEY_CANDIDATES = ("content", "value", "text", "message", "body", "parts")
JSON_CONTAINER_KEYS = ("messages", "message", "conversations", "conversation", "dialogue", "dialog", "turns", "history")

def _to_jsonable(value: Any) -> Any:
    if value is None: return None
    if isinstance(value, (str, int, float, bool)): return value
    if isinstance(value, dict): return {str(k): _to_jsonable(v) for k, v in value.items()}
    if isinstance(value, (list, tuple, set)): return [_to_jsonable(v) for v in value]
    return str(value)

def _serialize_content(value: Any) -> str:
    if isinstance(value, str): return value
    try: return json.dumps(_to_jsonable(value), ensure_ascii=False)
    except: return str(value)

def _maybe_parse_json_string(value: Any) -> Any:
    if not isinstance(value, str): return value
    text = value.strip()
    if not text or text[:1] not in {"[", "{"}: return value
    try: return json.loads(text)
    except: return value

def _normalize_role(value: Any, role_aliases: Optional[Dict[str, Iterable[str]]] = None) -> Optional[str]:
    if value is None: return None
    text = str(value).strip().lower()
    aliases = role_aliases or ROLE_ALIASES
    for canonical, names in aliases.items():
        if text == canonical or text in names: return canonical
    return None

def _lookup_key_case_insensitive(mapping: Dict[str, Any], target: str) -> Optional[str]:
    target_norm = str(target).strip().lower()
    for key in mapping.keys():
        if str(key).strip().lower() == target_norm: return key
    return None

def _is_message_like_dict(obj: Any) -> bool:
    if not isinstance(obj, dict): return False
    keys = {str(k).strip().lower() for k in obj.keys()}
    return bool(keys.intersection(ROLE_KEY_CANDIDATES) and keys.intersection(CONTENT_KEY_CANDIDATES))

def _unwrap_message_container(value: Any) -> Optional[List[Any]]:
    value = _maybe_parse_json_string(value)
    if isinstance(value, list):
        return value if any(isinstance(i, dict) for i in value) else None
    if isinstance(value, dict):
        for k in JSON_CONTAINER_KEYS:
            rk = _lookup_key_case_insensitive(value, k)
            if rk and isinstance(value[rk], list): return value[rk]
        if _is_message_like_dict(value): return [value]
    return None

def _normalize_aliases(spec: Dict[str, Any]) -> Dict[str, set[str]]:
    res = {r: set(v) for r, v in ROLE_ALIASES.items()}
    raw = spec.get("role_aliases", {})
    if isinstance(raw, dict):
        for c, vs in raw.items():
            cn = str(c).lower()
            if cn in TARGET_ROLES:
                if isinstance(vs, (list, tuple, set)): res[cn].update(str(v).lower() for v in vs if v)
                elif vs: res[cn].add(str(vs).lower())
    return res

def transform_row(record: Dict[str, Any], row_idx: int = 0) -> List[Dict[str, str]]:
    spec = PLAN
    alias_map = _normalize_aliases(spec)
    field_to_role = spec.get("field_to_role", {})
    conversation_candidates = spec.get("conversation_field_candidates", [])
    ordered_keys = spec.get("ordered_top_level_fields", list(record.keys()))
    
    candidate_keys = list(dict.fromkeys([*conversation_candidates, *ordered_keys]))
    messages = []
    
    for field in candidate_keys:
        if field not in record or record[field] is None: continue
        
        raw = record[field]
        nested = _unwrap_message_container(raw)
        if nested:
            rk = spec.get("role_key") or "role"
            ck = spec.get("content_key") or "content"
            for item in nested:
                if not isinstance(item, dict): continue
                found_rk = _lookup_key_case_insensitive(item, rk)
                found_ck = _lookup_key_case_insensitive(item, ck)
                if found_rk and found_ck:
                    role = _normalize_role(item.get(found_rk), alias_map)
                    if role: messages.append({"role": role, "content": _serialize_content(item.get(found_ck))})
            continue

        role = field_to_role.get(field)
        if role and role in TARGET_ROLES:
            messages.append({"role": role, "content": _serialize_content(raw)})
            
    return messages

# --- Example Usage ---
if __name__ == "__main__":
    test_record = {
    "input": "",
    "instruction": "How can I add a function to find the maximum number among a given set of numbers?",
    "output": "You can add the following function in your code to achieve this:\n\n```python\ndef find_max(numbers):\n    max_number = max(numbers)\n    return max_number\n```\n\nThis function takes a list of numbers as input and utilizes the `max()` function in Python to find the maximum among them. It then returns the maximum number.\n\nYou can call this function by passing the numbers you want to evaluate as a list. For example:\n\n```python\nnumbers = [10, 5, 23, 8, 1]\nmaximum = find_max(numbers)\nprint(\"The maximum number is:\", maximum)\n```\n\nIn the above example, the `numbers` list contains five integers. By calling the `find_max()` function with this list as the argument, it will return the maximum number among them. Finally, the result is printed out, which in this case would be `23`."
}
    print("Plan Transformation Result:")
    print(json.dumps(transform_row(test_record), indent=2))
